version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jonghoon
      POSTGRES_PASSWORD: jonghoon
    volumes:
      - ./data/:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
