version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jonghoon
      POSTGRES_PASSWORD: jonghoon
    volumes:
      - ./data/:/var/lib/postgresql/data
